server:
  port: 8001
mybatis:
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml # mapper文件位置
  config-location: classpath:mybatis/mybatis.cfg.xml  # 配置文件的位置
  type-aliases-package: com.github.fish56.cloud.entity # 实体类的位置
spring:
  application:
    name: cloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
